/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  text,
  jsonb,
  boolean,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default('0'),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const texts_top_citation = pgTable(
  'texts_top_citation',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    text: varchar('text'),
    author: varchar('author'),
    further: varchar('further'),
  },
  (columns) => [
    index('texts_top_citation_order_idx').on(columns._order),
    index('texts_top_citation_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [texts.id],
      name: 'texts_top_citation_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const texts_blocks_richtext = pgTable(
  'texts_blocks_richtext',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    content: jsonb('content').notNull(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('texts_blocks_richtext_order_idx').on(columns._order),
    index('texts_blocks_richtext_parent_id_idx').on(columns._parentID),
    index('texts_blocks_richtext_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [texts.id],
      name: 'texts_blocks_richtext_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const texts = pgTable(
  'texts',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    subtitle: varchar('subtitle'),
    author: varchar('author').notNull(),
    position: varchar('position'),
    extrainfo: varchar('extrainfo'),
    pdf: integer('pdf_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('texts_pdf_idx').on(columns.pdf),
    index('texts_updated_at_idx').on(columns.updatedAt),
    index('texts_created_at_idx').on(columns.createdAt),
  ],
)

export const pages_blocks_image = pgTable(
  'pages_blocks_image',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    title: varchar('title'),
    description: varchar('description'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_image_order_idx').on(columns._order),
    index('pages_blocks_image_parent_id_idx').on(columns._parentID),
    index('pages_blocks_image_path_idx').on(columns._path),
    index('pages_blocks_image_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_image_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages = pgTable(
  'pages',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('pages_updated_at_idx').on(columns.updatedAt),
    index('pages_created_at_idx').on(columns.createdAt),
  ],
)

export const pages_rels = pgTable(
  'pages_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    textsID: integer('texts_id'),
  },
  (columns) => [
    index('pages_rels_order_idx').on(columns.order),
    index('pages_rels_parent_idx').on(columns.parent),
    index('pages_rels_path_idx').on(columns.path),
    index('pages_rels_texts_id_idx').on(columns.textsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [pages.id],
      name: 'pages_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['textsID']],
      foreignColumns: [texts.id],
      name: 'pages_rels_texts_fk',
    }).onDelete('cascade'),
  ],
)

export const subpages_blocks_image = pgTable(
  'subpages_blocks_image',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    title: varchar('title'),
    description: varchar('description'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('subpages_blocks_image_order_idx').on(columns._order),
    index('subpages_blocks_image_parent_id_idx').on(columns._parentID),
    index('subpages_blocks_image_path_idx').on(columns._path),
    index('subpages_blocks_image_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [subpages.id],
      name: 'subpages_blocks_image_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const subpages = pgTable(
  'subpages',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    parentPage: integer('parent_page_id')
      .notNull()
      .references(() => pages.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('subpages_parent_page_idx').on(columns.parentPage),
    index('subpages_updated_at_idx').on(columns.updatedAt),
    index('subpages_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    textsID: integer('texts_id'),
    pagesID: integer('pages_id'),
    subpagesID: integer('subpages_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_texts_id_idx').on(columns.textsID),
    index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
    index('payload_locked_documents_rels_subpages_id_idx').on(columns.subpagesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['textsID']],
      foreignColumns: [texts.id],
      name: 'payload_locked_documents_rels_texts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['subpagesID']],
      foreignColumns: [subpages.id],
      name: 'payload_locked_documents_rels_subpages_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const homepage_blocks_hero = pgTable(
  'homepage_blocks_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    description: varchar('description'),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('homepage_blocks_hero_order_idx').on(columns._order),
    index('homepage_blocks_hero_parent_id_idx').on(columns._parentID),
    index('homepage_blocks_hero_path_idx').on(columns._path),
    index('homepage_blocks_hero_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [homepage.id],
      name: 'homepage_blocks_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const homepage_news = pgTable(
  'homepage_news',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    date: varchar('date'),
    titel: varchar('titel'),
    involved: varchar('involved'),
    location: varchar('location'),
  },
  (columns) => [
    index('homepage_news_order_idx').on(columns._order),
    index('homepage_news_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [homepage.id],
      name: 'homepage_news_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const homepage = pgTable('homepage', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const nav_links_nav_items_subpage_links = pgTable(
  'nav_links_nav_items_subpage_links',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label'),
    years: varchar('years'),
    link: varchar('link'),
  },
  (columns) => [
    index('nav_links_nav_items_subpage_links_order_idx').on(columns._order),
    index('nav_links_nav_items_subpage_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [nav_links_nav_items.id],
      name: 'nav_links_nav_items_subpage_links_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const nav_links_nav_items = pgTable(
  'nav_links_nav_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label'),
    years: varchar('years'),
    link: varchar('link'),
  },
  (columns) => [
    index('nav_links_nav_items_order_idx').on(columns._order),
    index('nav_links_nav_items_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [nav_links.id],
      name: 'nav_links_nav_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const nav_links = pgTable('nav_links', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const footer_nav = pgTable(
  'footer_nav',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label'),
    link: varchar('link'),
  },
  (columns) => [
    index('footer_nav_order_idx').on(columns._order),
    index('footer_nav_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [footer.id],
      name: 'footer_nav_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const footer = pgTable(
  'footer',
  {
    id: serial('id').primaryKey(),
    logo: integer('logo_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    copyrightNotice: varchar('copyright_notice').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [index('footer_logo_idx').on(columns.logo)],
)

export const exhibition_exhib_years_exhibitions = pgTable(
  'exhibition_exhib_years_exhibitions',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    description: varchar('description').notNull(),
    katalog: boolean('katalog'),
  },
  (columns) => [
    index('exhibition_exhib_years_exhibitions_order_idx').on(columns._order),
    index('exhibition_exhib_years_exhibitions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [exhibition_exhib_years.id],
      name: 'exhibition_exhib_years_exhibitions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const exhibition_exhib_years = pgTable(
  'exhibition_exhib_years',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    year: varchar('year').notNull(),
  },
  (columns) => [
    index('exhibition_exhib_years_order_idx').on(columns._order),
    index('exhibition_exhib_years_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [exhibition.id],
      name: 'exhibition_exhib_years_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const exhibition = pgTable('exhibition', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const exhibpart_year_exhib_part_exhibitions = pgTable(
  'exhibpart_year_exhib_part_exhibitions',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    description: varchar('description').notNull(),
    katalog: boolean('katalog'),
  },
  (columns) => [
    index('exhibpart_year_exhib_part_exhibitions_order_idx').on(columns._order),
    index('exhibpart_year_exhib_part_exhibitions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [exhibpart_year_exhib_part.id],
      name: 'exhibpart_year_exhib_part_exhibitions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const exhibpart_year_exhib_part = pgTable(
  'exhibpart_year_exhib_part',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    year: varchar('year').notNull(),
  },
  (columns) => [
    index('exhibpart_year_exhib_part_order_idx').on(columns._order),
    index('exhibpart_year_exhib_part_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [exhibpart.id],
      name: 'exhibpart_year_exhib_part_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const exhibpart = pgTable('exhibpart', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const acquis_acquisition_events = pgTable(
  'acquis_acquisition_events',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    description: varchar('description').notNull(),
  },
  (columns) => [
    index('acquis_acquisition_events_order_idx').on(columns._order),
    index('acquis_acquisition_events_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [acquis.id],
      name: 'acquis_acquisition_events_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const acquis = pgTable('acquis', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const cv_cv_events = pgTable(
  'cv_cv_events',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    year: varchar('year').notNull(),
    description: varchar('description').notNull(),
  },
  (columns) => [
    index('cv_cv_events_order_idx').on(columns._order),
    index('cv_cv_events_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cv.id],
      name: 'cv_cv_events_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const cv = pgTable('cv', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const contact = pgTable('contact', {
  id: serial('id').primaryKey(),
  contactDetails_name: varchar('contact_details_name').notNull(),
  contactDetails_address: varchar('contact_details_address').notNull(),
  contactDetails_email: varchar('contact_details_email').notNull(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_texts_top_citation = relations(texts_top_citation, ({ one }) => ({
  _parentID: one(texts, {
    fields: [texts_top_citation._parentID],
    references: [texts.id],
    relationName: 'top-citation',
  }),
}))
export const relations_texts_blocks_richtext = relations(texts_blocks_richtext, ({ one }) => ({
  _parentID: one(texts, {
    fields: [texts_blocks_richtext._parentID],
    references: [texts.id],
    relationName: '_blocks_richtext',
  }),
}))
export const relations_texts = relations(texts, ({ one, many }) => ({
  'top-citation': many(texts_top_citation, {
    relationName: 'top-citation',
  }),
  _blocks_richtext: many(texts_blocks_richtext, {
    relationName: '_blocks_richtext',
  }),
  pdf: one(media, {
    fields: [texts.pdf],
    references: [media.id],
    relationName: 'pdf',
  }),
}))
export const relations_pages_blocks_image = relations(pages_blocks_image, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_image._parentID],
    references: [pages.id],
    relationName: '_blocks_image',
  }),
  image: one(media, {
    fields: [pages_blocks_image.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_pages_rels = relations(pages_rels, ({ one }) => ({
  parent: one(pages, {
    fields: [pages_rels.parent],
    references: [pages.id],
    relationName: '_rels',
  }),
  textsID: one(texts, {
    fields: [pages_rels.textsID],
    references: [texts.id],
    relationName: 'texts',
  }),
}))
export const relations_pages = relations(pages, ({ many }) => ({
  _blocks_image: many(pages_blocks_image, {
    relationName: '_blocks_image',
  }),
  _rels: many(pages_rels, {
    relationName: '_rels',
  }),
}))
export const relations_subpages_blocks_image = relations(subpages_blocks_image, ({ one }) => ({
  _parentID: one(subpages, {
    fields: [subpages_blocks_image._parentID],
    references: [subpages.id],
    relationName: '_blocks_image',
  }),
  image: one(media, {
    fields: [subpages_blocks_image.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_subpages = relations(subpages, ({ one, many }) => ({
  parentPage: one(pages, {
    fields: [subpages.parentPage],
    references: [pages.id],
    relationName: 'parentPage',
  }),
  _blocks_image: many(subpages_blocks_image, {
    relationName: '_blocks_image',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    textsID: one(texts, {
      fields: [payload_locked_documents_rels.textsID],
      references: [texts.id],
      relationName: 'texts',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    subpagesID: one(subpages, {
      fields: [payload_locked_documents_rels.subpagesID],
      references: [subpages.id],
      relationName: 'subpages',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_homepage_blocks_hero = relations(homepage_blocks_hero, ({ one }) => ({
  _parentID: one(homepage, {
    fields: [homepage_blocks_hero._parentID],
    references: [homepage.id],
    relationName: '_blocks_hero',
  }),
  image: one(media, {
    fields: [homepage_blocks_hero.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_homepage_news = relations(homepage_news, ({ one }) => ({
  _parentID: one(homepage, {
    fields: [homepage_news._parentID],
    references: [homepage.id],
    relationName: 'news',
  }),
}))
export const relations_homepage = relations(homepage, ({ many }) => ({
  _blocks_hero: many(homepage_blocks_hero, {
    relationName: '_blocks_hero',
  }),
  news: many(homepage_news, {
    relationName: 'news',
  }),
}))
export const relations_nav_links_nav_items_subpage_links = relations(
  nav_links_nav_items_subpage_links,
  ({ one }) => ({
    _parentID: one(nav_links_nav_items, {
      fields: [nav_links_nav_items_subpage_links._parentID],
      references: [nav_links_nav_items.id],
      relationName: 'subpageLinks',
    }),
  }),
)
export const relations_nav_links_nav_items = relations(nav_links_nav_items, ({ one, many }) => ({
  _parentID: one(nav_links, {
    fields: [nav_links_nav_items._parentID],
    references: [nav_links.id],
    relationName: 'navItems',
  }),
  subpageLinks: many(nav_links_nav_items_subpage_links, {
    relationName: 'subpageLinks',
  }),
}))
export const relations_nav_links = relations(nav_links, ({ many }) => ({
  navItems: many(nav_links_nav_items, {
    relationName: 'navItems',
  }),
}))
export const relations_footer_nav = relations(footer_nav, ({ one }) => ({
  _parentID: one(footer, {
    fields: [footer_nav._parentID],
    references: [footer.id],
    relationName: 'nav',
  }),
}))
export const relations_footer = relations(footer, ({ one, many }) => ({
  logo: one(media, {
    fields: [footer.logo],
    references: [media.id],
    relationName: 'logo',
  }),
  nav: many(footer_nav, {
    relationName: 'nav',
  }),
}))
export const relations_exhibition_exhib_years_exhibitions = relations(
  exhibition_exhib_years_exhibitions,
  ({ one }) => ({
    _parentID: one(exhibition_exhib_years, {
      fields: [exhibition_exhib_years_exhibitions._parentID],
      references: [exhibition_exhib_years.id],
      relationName: 'exhibitions',
    }),
  }),
)
export const relations_exhibition_exhib_years = relations(
  exhibition_exhib_years,
  ({ one, many }) => ({
    _parentID: one(exhibition, {
      fields: [exhibition_exhib_years._parentID],
      references: [exhibition.id],
      relationName: 'exhibYears',
    }),
    exhibitions: many(exhibition_exhib_years_exhibitions, {
      relationName: 'exhibitions',
    }),
  }),
)
export const relations_exhibition = relations(exhibition, ({ many }) => ({
  exhibYears: many(exhibition_exhib_years, {
    relationName: 'exhibYears',
  }),
}))
export const relations_exhibpart_year_exhib_part_exhibitions = relations(
  exhibpart_year_exhib_part_exhibitions,
  ({ one }) => ({
    _parentID: one(exhibpart_year_exhib_part, {
      fields: [exhibpart_year_exhib_part_exhibitions._parentID],
      references: [exhibpart_year_exhib_part.id],
      relationName: 'exhibitions',
    }),
  }),
)
export const relations_exhibpart_year_exhib_part = relations(
  exhibpart_year_exhib_part,
  ({ one, many }) => ({
    _parentID: one(exhibpart, {
      fields: [exhibpart_year_exhib_part._parentID],
      references: [exhibpart.id],
      relationName: 'yearExhibPart',
    }),
    exhibitions: many(exhibpart_year_exhib_part_exhibitions, {
      relationName: 'exhibitions',
    }),
  }),
)
export const relations_exhibpart = relations(exhibpart, ({ many }) => ({
  yearExhibPart: many(exhibpart_year_exhib_part, {
    relationName: 'yearExhibPart',
  }),
}))
export const relations_acquis_acquisition_events = relations(
  acquis_acquisition_events,
  ({ one }) => ({
    _parentID: one(acquis, {
      fields: [acquis_acquisition_events._parentID],
      references: [acquis.id],
      relationName: 'acquisitionEvents',
    }),
  }),
)
export const relations_acquis = relations(acquis, ({ many }) => ({
  acquisitionEvents: many(acquis_acquisition_events, {
    relationName: 'acquisitionEvents',
  }),
}))
export const relations_cv_cv_events = relations(cv_cv_events, ({ one }) => ({
  _parentID: one(cv, {
    fields: [cv_cv_events._parentID],
    references: [cv.id],
    relationName: 'cvEvents',
  }),
}))
export const relations_cv = relations(cv, ({ many }) => ({
  cvEvents: many(cv_cv_events, {
    relationName: 'cvEvents',
  }),
}))
export const relations_contact = relations(contact, () => ({}))

type DatabaseSchema = {
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  texts_top_citation: typeof texts_top_citation
  texts_blocks_richtext: typeof texts_blocks_richtext
  texts: typeof texts
  pages_blocks_image: typeof pages_blocks_image
  pages: typeof pages
  pages_rels: typeof pages_rels
  subpages_blocks_image: typeof subpages_blocks_image
  subpages: typeof subpages
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  homepage_blocks_hero: typeof homepage_blocks_hero
  homepage_news: typeof homepage_news
  homepage: typeof homepage
  nav_links_nav_items_subpage_links: typeof nav_links_nav_items_subpage_links
  nav_links_nav_items: typeof nav_links_nav_items
  nav_links: typeof nav_links
  footer_nav: typeof footer_nav
  footer: typeof footer
  exhibition_exhib_years_exhibitions: typeof exhibition_exhib_years_exhibitions
  exhibition_exhib_years: typeof exhibition_exhib_years
  exhibition: typeof exhibition
  exhibpart_year_exhib_part_exhibitions: typeof exhibpart_year_exhib_part_exhibitions
  exhibpart_year_exhib_part: typeof exhibpart_year_exhib_part
  exhibpart: typeof exhibpart
  acquis_acquisition_events: typeof acquis_acquisition_events
  acquis: typeof acquis
  cv_cv_events: typeof cv_cv_events
  cv: typeof cv
  contact: typeof contact
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_texts_top_citation: typeof relations_texts_top_citation
  relations_texts_blocks_richtext: typeof relations_texts_blocks_richtext
  relations_texts: typeof relations_texts
  relations_pages_blocks_image: typeof relations_pages_blocks_image
  relations_pages_rels: typeof relations_pages_rels
  relations_pages: typeof relations_pages
  relations_subpages_blocks_image: typeof relations_subpages_blocks_image
  relations_subpages: typeof relations_subpages
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_homepage_blocks_hero: typeof relations_homepage_blocks_hero
  relations_homepage_news: typeof relations_homepage_news
  relations_homepage: typeof relations_homepage
  relations_nav_links_nav_items_subpage_links: typeof relations_nav_links_nav_items_subpage_links
  relations_nav_links_nav_items: typeof relations_nav_links_nav_items
  relations_nav_links: typeof relations_nav_links
  relations_footer_nav: typeof relations_footer_nav
  relations_footer: typeof relations_footer
  relations_exhibition_exhib_years_exhibitions: typeof relations_exhibition_exhib_years_exhibitions
  relations_exhibition_exhib_years: typeof relations_exhibition_exhib_years
  relations_exhibition: typeof relations_exhibition
  relations_exhibpart_year_exhib_part_exhibitions: typeof relations_exhibpart_year_exhib_part_exhibitions
  relations_exhibpart_year_exhib_part: typeof relations_exhibpart_year_exhib_part
  relations_exhibpart: typeof relations_exhibpart
  relations_acquis_acquisition_events: typeof relations_acquis_acquisition_events
  relations_acquis: typeof relations_acquis
  relations_cv_cv_events: typeof relations_cv_cv_events
  relations_cv: typeof relations_cv
  relations_contact: typeof relations_contact
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
